copies=Y
classification_number_pref=LOC_
classification_number_format=if p(v90) then ,v90^a,|.|v90^b,|.|v90^c,|.|v90^d fi
inventory_number_pref=CN_
inventory_number_format=V1
inventory_number_pref_list=CN_
inventory_number_display=V1
label_format=@barcode.pft
label_format_txt=@barcodetxt.pft
height=4
width=7
cols=3
