<?php

/**
 * @file       stats_ajax.php
 * @brief      This script processes AJAX requests for generating statistical tables in the ABCD.
 *             It handles character encoding conversions between JavaScript (UTF-8) and PHP (ISO-8859-1),
 *             retrieves data based on the provided parameters, and returns an HTML table as a response.
 * @author      Roger Craveiro Guilherme
 * @date        2026-05-08
 */

session_start();
include("../common/get_post.php");
include("../config.php");
include("../lang/statistics.php");
include("../lang/admin.php");

if (!isset($_SESSION["permiso"])) die("Sessão expirada.");

// 1. Detects the encoding of the parameters sent by JS (default to ISO-8859-1 if not set)
$charset = isset($meta_encoding) ? strtoupper($meta_encoding) : "ISO-8859-1";

// 2. BRIDGE FUNCTION (INPUT): Converts UTF-8 parameters in JavaScript to ISO-8859-1
function decode_param_from_js($param, $charset)
{
    $param = urldecode($param);
    if ($charset == "ISO-8859-1" || $charset == "ANSI") {
        return mb_convert_encoding($param, 'ISO-8859-1', 'UTF-8');
    }
    return $param;
}

if (isset($arrHttp["tables"])) $arrHttp["tables"] = decode_param_from_js($arrHttp["tables"], $charset);
if (isset($arrHttp["rows"])) $arrHttp["rows"] = decode_param_from_js($arrHttp["rows"], $charset);
if (isset($arrHttp["cols"])) $arrHttp["cols"] = decode_param_from_js($arrHttp["cols"], $charset);
if (isset($arrHttp["proc"])) $arrHttp["proc"] = decode_param_from_js($arrHttp["proc"], $charset);

include("tables_generate_inc.php");

$tab = array();
$rows = array();
$cols = array();
$tabs = array();
$tipo = array();
$filter_date = array();

$tab_vars = LeerVariables($db_path, $arrHttp, $lang_db);
$Formato = ConstruirFormato($arrHttp, $lang_db, $tab_vars, $db_path);

$contenido = SeleccionarRegistros($arrHttp, $db_path, $Formato, $xWxis);

LeerRegistros($contenido);

// 3. STARTING THE BUFFER: We'll store the HTML output in memory instead of printing it directly
ob_start();

if (empty($tab)) {
    echo "<div style='padding:20px; color:#d9534f; background:#f9f2f2; border:1px solid #dca7a7; text-align:center; border-radius:4px;'>Nenhum dado encontrado para os parâmetros selecionados. Verifique a expressão ou o intervalo MFN.</div>";
} else {
    ConstruirSalida($tab, $tabs, $tipo, $rows, $cols);
}

// 4. SCREENSHOT OF THE GENERATED TABLE: We capture the HTML output generated by the ConstruirSalida function
$html_final = ob_get_clean();

// 5. BRIDGE FUNCTION (OUTPUT): We inform JS that the data will be sent in UTF-8 and convert the output
header("Content-Type: text/html; charset=UTF-8");

if ($charset == "ISO-8859-1" || $charset == "ANSI") {
    echo mb_convert_encoding($html_final, 'UTF-8', 'ISO-8859-1');
} else {
    echo $html_final;
}
